<a href="https://colab.research.google.com/github/cange017/SparkDev-Code-Alongs/blob/master/ImageClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# MNIST data image classfier with keras

# 1. load the dataset and libraries
from keras.datasets import mnist 
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
from keras import models
from keras import layers

In [0]:
# 2. Preprocess the data
#flatten out the input data into a 784x1 vector, convert pixel values from uint8 to float32, and range from 
# 0 255 to the interval [0,1]
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32') / 255


In [0]:
# 3. Create the model, in this case, we will use a sequential one
network = models.Sequential()

# make two layer-neural network
# layer one with 512 nodes (arbitrary) and relu as activation function, input_shape is the input dimension expected by the layer
# here, it is 28 by 28 pixel, flattened to 784 x 1 vector
network.add(layers.Dense(512, activation='relu',input_shape=(28*28,)))

# output layer 
network.add(layers.Dense(10, activation='softmax'))

#compile the network by providing the optimizer, loss function and the metrics to monitor
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])



In [27]:
# 4. One-hot encoding to binarize the data to better predict
# convert the labels to one hot vector form to convert
# Example , the one hot vector representation for 0, 1, and 2 would look like:
# class 0 => [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# class 1 => [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
# class 2 => [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
# dimension equals number of classes (10)
# every value in the vector is zero except for the index that corresponds to that particular digit
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print(train_labels)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [28]:
# 5. Train the model

# epochs is the number of times you iterate over the entire dataset
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 4s 68us/step - loss: 0.2553 - acc: 0.9266
Epoch 2/5
60000/60000 [==============================] - 4s 67us/step - loss: 0.1023 - acc: 0.9703
Epoch 3/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.0681 - acc: 0.9805
Epoch 4/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.0489 - acc: 0.9851
Epoch 5/5
60000/60000 [==============================] - 4s 68us/step - loss: 0.0372 - acc: 0.9889


In [29]:
# 6. Evaluate the model on the test data.
test_loss, test_acc = network.evaluate(test_images, test_labels)

print('test accuracy: ', test_acc)

10000/10000 [==============================] - 1s 54us/step
test accuracy:  0.9785
